### ISSUE TITLE
WebStorm 2023.3.2 with Copilot and Inspection Lens not supported?

### ISSUE THREAD

**Issue by adaliszk** [typed-rocks/witt#1]
Hi there, hello!

It's a fantastic plugin; it's something that I was looking for. However, I cannot seem to force it to work 😢 

I am running WebStorm 2023.3.2 with a few related plugins like Copilot and Inspection Lens. The project is a monorepo with typescript 4.9.5.

![image](https://github.com/typed-rocks/witt/assets/5189131/4ae75aec-3ba3-4c73-91e4-c00d73a11b19)

Is there anything I am doing wrong here, or are there some known incompatibilities I should know?

**Comment by chwoerz** [comment]
Does it work if you run the //^? On a type? I will check it if it works as soon as I come today.  

Is your typescript service running? You can check on the lower right corner of the ide when you click on typescript.

**Comment by adaliszk** [comment]
Like this?
![image](https://github.com/typed-rocks/witt/assets/5189131/877d7961-e901-4ab5-8622-587068312b97)

The service seems to be running; restarting it had no effect.
![image](https://github.com/typed-rocks/witt/assets/5189131/0e068009-2ce7-4f81-8a9f-026068a73eca)

Interestingly though it is not a simple Typescript service, but Vue Typescript.

**Comment by chwoerz** [comment]
Hmm interesting. Maybe it does not work in combination with vue currently. Could you create a project or a file somewhere else without vue plugin running?

I will check it and come back to you. Thank you for opening this issue.

**Comment by adaliszk** [comment]
I have the same issue with my https://github.com/adaliszk/node-toolbox

![image](https://github.com/typed-rocks/witt/assets/5189131/010bd4be-3dd9-47cc-b4b6-2d474af74586)

Inspector Lens resolves the types nicely, but the comment does nothing. When I type it, Copilot tries to autocomplete it. Perhaps it has to do with their hijacking of the suggestion system?

**Comment by chwoerz** [comment]
Perfect that you have a project where I can try it. Will come back to you with a solution. 👍

**Comment by chwoerz** [comment]
@adaliszk I got the issue. Somehow if the the check is in a function it wont work. Will work on a solution and sand you a version to test with soon.

Could you please check if it works for you if you do it on the top level of a file?

**Comment by chwoerz** [comment]
[witt-1.0.4.zip](https://github.com/typed-rocks/witt/files/13967191/witt-1.0.4.zip)

This version should work. Could you please remove my current plugin and install this? Just use "Install Plugin From Disk" and choose this zip file. At the plugin settings-page where you normally install the plugins. (The gear icon) If you need any help, contact me :)

**Comment by adaliszk** [comment]
Ah, nice catch! It works now, thank you very much!

![image](https://github.com/typed-rocks/witt/assets/5189131/3825e7b7-2791-465a-99eb-c11c57503fda)

**Comment by chwoerz** [comment]
Many thanks for your issue. I will release the new version ASAP

**Comment by adaliszk** [comment]
Thanks for the quick fix, and having this plugin in the first place!

**Comment by chwoerz** [comment]
The new version 1.0.5 is released containing the fix

**Comment by matiaslauriti** [comment]
It is still not working for me inside Nuxt 3. I even open a composable file that exclusively have `.ts` and is doing nothing at all (on latest version `1.0.9`)
