### ISSUE TITLE
This extension is incompatible with version 243.* of Webstorm

### ISSUE THREAD

**Issue by epoiate** [typed-rocks/witt#2]
Webstorm version 2024.3 (Build #WS-243.21565.180, built on November 12, 2024) shows the following message:

`Incompatible: requires IDE build 242.* or earlier`

I'm using Ubuntu 22.04

**Comment by chwoerz** [comment]
Thank you. I will update it ASAP

**Comment by PatrickLehner-Kraken** [comment]
Sorry to bump this @chwoerz, could you take a look at @wingy3181's PR #3 and merge it if it looks good? 🙏 

Would love to try this plugin in the current version of IntelliJ

**Comment by 0xdevalias** [comment]
> > I will close this PR as soon as Jetbrains approved it.
> 
> Looks like it's been approved and is available now:
> 
> - https://plugins.jetbrains.com/plugin/23294-witt--typescript-type-hints-like-in-the-ts-playground/versions
>   - <img width="821" alt="image" src="https://github.com/user-attachments/assets/e727733a-565b-41bb-bad7-c8c72f6445aa" />
> 
> _Originally posted by @0xdevalias in https://github.com/typed-rocks/witt/issues/3#issuecomment-2564416433_
